name: braintree_paypal
description: A new Flutter project.
version: 0.0.3
#homepage:

environment:
  sdk: '>=3.1.5 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  plugin:
    platforms:
      android:
        package: dev.jonmlk.braintree_paypal
        pluginClass: BraintreePaypalPlugin
      ios:
        pluginClass: BraintreePaypalPlugin
      web:
        pluginClass: BraintreePaypalWeb
        fileName: platform/braintree_paypal_web.dart